apiVersion: v1
kind: Service
metadata:
  name: nipun-ai-worker
  namespace: nipun-ai
  annotations:
    metallb.universe.tf/allow-shared-ip: nipun-ai
  labels:
    app.kubernetes.io/name: nipun-ai-worker
    app.kubernetes.io/part-of: nipun-ai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nipun-ai-worker
  ports:
    - name: http
      protocol: TCP
      port: 8787
      targetPort: 8787
