apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - terminal-deployment.yaml
  - terminal-service.yaml
  - cert-issuer.yaml
  - certificate.yaml
  - gateway-configmap.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml

